# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The number of periods since x was positive (churn).
#'
#' @param x input numeric vector
#' @return periods since last positive value
cpp_churn <- function(x) {
    .Call('_bwmisc_cpp_churn', PACKAGE = 'bwmisc', x)
}

